import { inputSchemas, calculateCost, planMeeting, planRecurring, calculateSubscriptionStack, cronNextRuns } from './tool-contracts.js';
import { MODEL_PRICING, modelCatalogUpdatedAt } from './model-catalog.js';
import outputSchemas from './data/output-schemas.json';
import { toolResultUrl } from './tool-result-link.js';

const money=(n:number|null) => n===null ? 'unlisted' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(n);
export const MCP_TOOLS = [
  {name:'ai_api_cost',title:'AI API cost',slug:'ai-api-cost-calculator',description:'Estimate API workload costs in USD per request, day and month, with rates and dated snapshot provenance. Use for token budgets; use ai_subscription_stack_cost for chat or coding subscriptions. Model IDs use providerId/id from https://operatornest.com/api/models?subset=pricing, filtered to the MCP catalog; the OSS bundle lists accepted IDs in src/data/pricing-snapshot.json. Rates stay offline until the catalog is updated; missing rates return null. Cached tokens are part of total input; published batch and long-context rates apply only when eligible. Non-token charges are excluded.',compute:(raw:unknown) => calculateCost(raw,MODEL_PRICING,modelCatalogUpdatedAt),answer:(r:ReturnType<typeof calculateCost>) => r.estimates.map(e => `${e.name}: ${money(e.perRequest)}/request; ${money(e.perDay)}/day; ${money(e.perMonth)}/month.`).join('\n'),outputSchema:outputSchemas['ai-api-cost-calculator']},
  {name:'meeting_time_zones',title:'Meeting time zones',slug:'meeting-time-zone-planner',description:'Find shared 30-minute meeting slots inside 09:00–17:00 for 2–8 participants. Use to compare workday overlap; use recurring_schedule for repeating task calendars or cron_next_runs for scheduler previews. Returns all candidates, overlap count and up to three best slots ranked nearest to each person’s 13:00, with UTC starts and local labels. The date belongs to the first participant’s zone; daylight saving uses runtime IANA data. No calendar availability or holiday lookup, invitations or calendar writes.',compute:planMeeting,answer:(r:ReturnType<typeof planMeeting>) => `${r.overlapCount} shared half-hour slots.\n${r.bestSlots.map(s => `${s.startUtc}: ${r.input.people.map((p,i) => `${p.name}: ${s.labels[i]}`).join('; ')}`).join('\n')}`,outputSchema:outputSchemas['meeting-time-zone-planner']},
  {name:'recurring_schedule',title:'Recurring schedule',slug:'recurring-task-planner',description:'Prepare weekly, biweekly or monthly task calendars and estimate monthly effort for up to 20 tasks. Use to draft a recurring work plan; use cron_next_runs to preview existing cron syntax or meeting_time_zones for shared workday slots. Returns monthly hours, first dates, recurrence rules and an RFC 5545 calendar. Times float in the importing calendar’s local zone; weekly estimates use 52/12 runs per month and biweekly 26/12. owner is a planning label, with no assignment or execution. No calendar is updated; an empty task list returns zero hours and no events.',compute:planRecurring,answer:(r:ReturnType<typeof planRecurring>) => `${r.monthlyHours.toFixed(2)} hours/month.\n${r.schedules.map(s => `${s.title}: first ${s.firstDate} at ${s.time}; ${s.recurrenceRule}; ${s.minutes} minutes/run.`).join('\n')}\n${r.ics}`,outputSchema:outputSchemas['recurring-task-planner']},
  {name:'ai_subscription_stack_cost',title:'AI subscription stack cost',slug:'ai-subscription-cost-calculator',description:'Total selected AI chat and coding subscriptions in USD and identify overlapping capabilities. Use to review a subscription stack; use ai_api_cost for API token charges. Select unique planIds from the schema enum; [] returns zero totals and no plans. Returns monthly and annual totals, selected plans, capability groups and dated official sources. Annual totals use published annual billing or twelve monthly charges; taxes, regional differences and promotions are excluded. Bundled rates are dated estimates, without live billing lookup or subscription changes.',compute:calculateSubscriptionStack,answer:(r:ReturnType<typeof calculateSubscriptionStack>) => `${money(r.monthlyTotal)}/month; ${money(r.annualTotal)}/year.\n${r.plans.map(p => `${p.name}: ${money(p.monthly)}/month; ${money(p.annual ?? p.monthly*12)}/year${p.annual===null ? ' (twelve monthly charges)' : ''}. Source: ${p.source}, checked ${p.checked}.`).join('\n')}\nCapability overlaps: ${r.overlap.filter(c => c.planIds.length>1).map(c => `${c.label} (${c.planIds.join(', ')})`).join('; ') || 'none'}.`,outputSchema:outputSchemas['ai-subscription-cost-calculator']},
  {name:'cron_next_runs',title:'Cron next runs',slug:'cron-expression-generator',description:'Preview up to 10 cron matches strictly after a supplied UTC instant, within a 366-day search. Use to check existing scheduler syntax; use recurring_schedule to draft task recurrence calendars or meeting_time_zones for participant overlap. Returns UTC starts, local labels, normalized inputs and a dated syntax source; fewer matches or [] means the search window ended. Supports numeric stars, lists, ranges, steps and weekday names in the selected dialect; rejects L, W, # and named months. cloudflare requires UTC; other zones follow runtime daylight saving transitions. No schedule is installed or run.',compute:cronNextRuns,answer:(r:ReturnType<typeof cronNextRuns>) => r.runs.length ? r.runs.map(run => `${run.startUtc}: ${run.label}`).join('\n') : 'No matching time in the next 366 days.',outputSchema:outputSchemas['cron-expression-generator']},
].map(tool => ({...tool,inputSchema:inputSchemas[tool.slug as keyof typeof inputSchemas],annotations:{title:tool.title,readOnlyHint:true,openWorldHint:false,destructiveHint:false,idempotentHint:true}}));

export function callMcpTool(tool:typeof MCP_TOOLS[number],input:unknown) {
  const result=tool.compute(input);
  const url=toolResultUrl(tool.slug,result.input);
  // Full calculation first, with units, method, assumptions and provenance in both representations.
  return {content:[{type:'text' as const,text:`${(tool.answer as (r:any) => string)(result)}\n${JSON.stringify(result)}\nOpen this result: ${url}`}],structuredContent:result};
}
