import { inputSchemas, calculateCost, planMeeting, planRecurring, calculateSubscriptionStack, cronNextRuns } from './tool-contracts.js';
import { MODEL_PRICING, modelCatalogUpdatedAt } from './model-catalog.js';
import outputSchemas from './data/output-schemas.json';
import { toolResultUrl } from './tool-result-link.js';

const money=(n:number|null) => n===null ? 'unlisted' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(n);
export const MCP_TOOLS = [
  {name:'ai_api_cost',title:'AI API cost',slug:'ai-api-cost-calculator',description:'Estimate USD per request, day and month from token counts, caching and published batch discounts. Use for an API workload budget, not chat subscriptions. Model IDs use providerId/id from the bundled src/data/pricing-snapshot.json catalog. Rates are from the dated catalog snapshot returned with the result.',compute:(raw:unknown) => calculateCost(raw,MODEL_PRICING,modelCatalogUpdatedAt),answer:(r:ReturnType<typeof calculateCost>) => r.estimates.map(e => `${e.name}: ${money(e.perRequest)}/request; ${money(e.perDay)}/day; ${money(e.perMonth)}/month.`).join('\n'),outputSchema:outputSchemas['ai-api-cost-calculator']},
  {name:'meeting_time_zones',title:'Meeting time zones',slug:'meeting-time-zone-planner',description:'Find 30-minute meeting times inside 09:00–17:00 for 2–8 people in IANA time zones. The date is local to the first person. Applies daylight saving changes; does not read calendars or send invitations.',compute:planMeeting,answer:(r:ReturnType<typeof planMeeting>) => `${r.overlapCount} shared half-hour slots.\n${r.bestSlots.map(s => `${s.startUtc}: ${r.input.people.map((p,i) => `${p.name}: ${s.labels[i]}`).join('; ')}`).join('\n')}`,outputSchema:outputSchemas['meeting-time-zone-planner']},
  {name:'recurring_schedule',title:'Recurring schedule',slug:'recurring-task-planner',description:'Estimate monthly hours for weekly, biweekly and monthly tasks and return recurrence rules plus a complete RFC 5545 calendar. Use to prepare a schedule; no task is executed or calendar updated. Times float in the importing calendar’s local time zone.',compute:planRecurring,answer:(r:ReturnType<typeof planRecurring>) => `${r.monthlyHours.toFixed(2)} hours/month.\n${r.schedules.map(s => `${s.title}: first ${s.firstDate} at ${s.time}; ${s.recurrenceRule}; ${s.minutes} minutes/run.`).join('\n')}\n${r.ics}`,outputSchema:outputSchemas['recurring-task-planner']},
  {name:'ai_subscription_stack_cost',title:'AI subscription stack cost',slug:'ai-subscription-cost-calculator',description:'Total selected AI chat and coding subscriptions in USD and identify overlapping capabilities. Returns monthly charges, annual billing or twelve-charge estimates, plans and dated official sources. Use for reviewing a subscription stack, not API token costs.',compute:calculateSubscriptionStack,answer:(r:ReturnType<typeof calculateSubscriptionStack>) => `${money(r.monthlyTotal)}/month; ${money(r.annualTotal)}/year.\n${r.plans.map(p => `${p.name}: ${money(p.monthly)}/month; ${money(p.annual ?? p.monthly*12)}/year${p.annual===null ? ' (twelve monthly charges)' : ''}. Source: ${p.source}, checked ${p.checked}.`).join('\n')}\nCapability overlaps: ${r.overlap.filter(c => c.planIds.length>1).map(c => `${c.label} (${c.planIds.join(', ')})`).join('; ') || 'none'}.`,outputSchema:outputSchemas['ai-subscription-cost-calculator']},
  {name:'cron_next_runs',title:'Cron next runs',slug:'cron-expression-generator',description:'Preview 1–10 cron matches strictly after a supplied UTC instant within 366 days, in an IANA time zone. Supports numeric stars, lists, ranges, steps and weekday names for GitHub, Cloudflare, Quartz and AWS dialects. L, W, # and named months are rejected. This does not install or run a schedule.',compute:cronNextRuns,answer:(r:ReturnType<typeof cronNextRuns>) => r.runs.length ? r.runs.map(run => `${run.startUtc}: ${run.label}`).join('\n') : 'No matching time in the next 366 days.',outputSchema:outputSchemas['cron-expression-generator']},
].map(tool => ({...tool,inputSchema:inputSchemas[tool.slug as keyof typeof inputSchemas],annotations:{readOnlyHint:true,openWorldHint:false,destructiveHint:false,idempotentHint:true}}));

export function callMcpTool(tool:typeof MCP_TOOLS[number],input:unknown) {
  const result=tool.compute(input);
  const url=toolResultUrl(tool.slug,result.input);
  // Full calculation first, with units, method, assumptions and provenance in both representations.
  return {content:[{type:'text' as const,text:`${(tool.answer as (r:any) => string)(result)}\n${JSON.stringify(result)}\nOpen this result: ${url}`}],structuredContent:result};
}
